/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as MatchesNewRouteImport } from './routes/matches.new'
import { Route as HistorySessionIdRouteImport } from './routes/history_.$sessionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesNewRoute = MatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/history_/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jornada': typeof JornadaRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/matches/new': typeof MatchesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jornada': typeof JornadaRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/matches/new': typeof MatchesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jornada': typeof JornadaRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/history_/$sessionId': typeof HistorySessionIdRoute
  '/matches/new': typeof MatchesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/jornada'
    | '/players'
    | '/profile'
    | '/stats'
    | '/history/$sessionId'
    | '/matches/new'
    | '/sessions/new'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/jornada'
    | '/players'
    | '/profile'
    | '/stats'
    | '/history/$sessionId'
    | '/matches/new'
    | '/sessions/new'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/jornada'
    | '/players'
    | '/profile'
    | '/stats'
    | '/history_/$sessionId'
    | '/matches/new'
    | '/sessions/new'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  JornadaRoute: typeof JornadaRoute
  PlayersRoute: typeof PlayersRoute
  ProfileRoute: typeof ProfileRoute
  StatsRoute: typeof StatsRoute
  HistorySessionIdRoute: typeof HistorySessionIdRoute
  MatchesNewRoute: typeof MatchesNewRoute
  SessionsNewRoute: typeof SessionsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/new': {
      id: '/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof MatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$sessionId': {
      id: '/history_/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  JornadaRoute: JornadaRoute,
  PlayersRoute: PlayersRoute,
  ProfileRoute: ProfileRoute,
  StatsRoute: StatsRoute,
  HistorySessionIdRoute: HistorySessionIdRoute,
  MatchesNewRoute: MatchesNewRoute,
  SessionsNewRoute: SessionsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
