/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as MatchesNewRouteImport } from './routes/matches.new'
import { Route as DashboardStatsRouteImport } from './routes/_dashboard.stats'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardPlayersRouteImport } from './routes/_dashboard.players'
import { Route as DashboardJornadaRouteImport } from './routes/_dashboard.jornada'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard.history'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardTournamentsTournamentIdRouteImport } from './routes/_dashboard.tournaments_.$tournamentId'
import { Route as DashboardTournamentsNewRouteImport } from './routes/_dashboard.tournaments.new'
import { Route as DashboardHistorySessionIdRouteImport } from './routes/_dashboard.history_.$sessionId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesNewRoute = MatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlayersRoute = DashboardPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJornadaRoute = DashboardJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTournamentsTournamentIdRoute =
  DashboardTournamentsTournamentIdRouteImport.update({
    id: '/tournaments_/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTournamentsNewRoute = DashboardTournamentsNewRouteImport.update({
  id: '/tournaments/new',
  path: '/tournaments/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistorySessionIdRoute =
  DashboardHistorySessionIdRouteImport.update({
    id: '/history_/$sessionId',
    path: '/history/$sessionId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/history': typeof DashboardHistoryRoute
  '/jornada': typeof DashboardJornadaRoute
  '/players': typeof DashboardPlayersRoute
  '/profile': typeof DashboardProfileRoute
  '/stats': typeof DashboardStatsRoute
  '/matches/new': typeof MatchesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/history/$sessionId': typeof DashboardHistorySessionIdRoute
  '/tournaments/new': typeof DashboardTournamentsNewRoute
  '/tournaments/$tournamentId': typeof DashboardTournamentsTournamentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/history': typeof DashboardHistoryRoute
  '/jornada': typeof DashboardJornadaRoute
  '/players': typeof DashboardPlayersRoute
  '/profile': typeof DashboardProfileRoute
  '/stats': typeof DashboardStatsRoute
  '/matches/new': typeof MatchesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/': typeof DashboardIndexRoute
  '/history/$sessionId': typeof DashboardHistorySessionIdRoute
  '/tournaments/new': typeof DashboardTournamentsNewRoute
  '/tournaments/$tournamentId': typeof DashboardTournamentsTournamentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/jornada': typeof DashboardJornadaRoute
  '/_dashboard/players': typeof DashboardPlayersRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/stats': typeof DashboardStatsRoute
  '/matches/new': typeof MatchesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/history_/$sessionId': typeof DashboardHistorySessionIdRoute
  '/_dashboard/tournaments/new': typeof DashboardTournamentsNewRoute
  '/_dashboard/tournaments_/$tournamentId': typeof DashboardTournamentsTournamentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/jornada'
    | '/players'
    | '/profile'
    | '/stats'
    | '/matches/new'
    | '/sessions/new'
    | '/history/$sessionId'
    | '/tournaments/new'
    | '/tournaments/$tournamentId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/history'
    | '/jornada'
    | '/players'
    | '/profile'
    | '/stats'
    | '/matches/new'
    | '/sessions/new'
    | '/'
    | '/history/$sessionId'
    | '/tournaments/new'
    | '/tournaments/$tournamentId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/history'
    | '/_dashboard/jornada'
    | '/_dashboard/players'
    | '/_dashboard/profile'
    | '/_dashboard/stats'
    | '/matches/new'
    | '/sessions/new'
    | '/_dashboard/'
    | '/_dashboard/history_/$sessionId'
    | '/_dashboard/tournaments/new'
    | '/_dashboard/tournaments_/$tournamentId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  MatchesNewRoute: typeof MatchesNewRoute
  SessionsNewRoute: typeof SessionsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/new': {
      id: '/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof MatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/stats': {
      id: '/_dashboard/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/players': {
      id: '/_dashboard/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof DashboardPlayersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/jornada': {
      id: '/_dashboard/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof DashboardJornadaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/tournaments_/$tournamentId': {
      id: '/_dashboard/tournaments_/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof DashboardTournamentsTournamentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tournaments/new': {
      id: '/_dashboard/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof DashboardTournamentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/history_/$sessionId': {
      id: '/_dashboard/history_/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof DashboardHistorySessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardJornadaRoute: typeof DashboardJornadaRoute
  DashboardPlayersRoute: typeof DashboardPlayersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardHistorySessionIdRoute: typeof DashboardHistorySessionIdRoute
  DashboardTournamentsNewRoute: typeof DashboardTournamentsNewRoute
  DashboardTournamentsTournamentIdRoute: typeof DashboardTournamentsTournamentIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardJornadaRoute: DashboardJornadaRoute,
  DashboardPlayersRoute: DashboardPlayersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardHistorySessionIdRoute: DashboardHistorySessionIdRoute,
  DashboardTournamentsNewRoute: DashboardTournamentsNewRoute,
  DashboardTournamentsTournamentIdRoute: DashboardTournamentsTournamentIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  MatchesNewRoute: MatchesNewRoute,
  SessionsNewRoute: SessionsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
